# Bot Config
Bot :
  # HTTP通信
  http :
    coolq_http_api_ip : "127.0.0.1"
    coolq_http_api_port : "5700"

  # Mysql连接信息
  mysql :
    db_host : "127.0.0.1"
    db_port : 3306
    db_user : "bot_admin"
    db_passwd : "Huawei12#$"
    db_database : "mybot"
    db_charset : "utf8mb4"

  # 管理员信息配置
  admin :
    uid : 3012797743


# 用户管控 不建议改动
Level :
  # 用户权限
  user :
    general : 10
    vip : 50
    admin : 999
  # 群组权限
  group :
    general : 10
    vip : 50
  # 普通用户调用频率限制
  user_limit: 
    enable: True  # or False
    seconds: 10   # user_limit_cycle



# Plugin Config
Plugin :
  saucenao :
    api_key : "f8c6827c4a9e6eef82267d5a0f1da48d067a87d1"


# Debug Config
Debug : True