# Bot Config
Bot :
  coolq_http_api_ip : "127.0.0.1"
  coolq_http_api_port : "5700"

  # Mysql连接信息
  mysql :
    db_host : "127.0.0.1"
    db_port : 3306
    db_user : "bot_admin"
    db_passwd : "Huawei12#$"
    db_database : "mybot"
    db_charset : "utf8mb4"

  # 用户及群组默认权限
  level :
    user :
      general : 10
      vip : 50
      admin : 999
    group :
      general : 10
      vip : 50
      

# Plugin Config
Plugin :
  saucenao :
    api_key : "f8c6827c4a9e6eef82267d5a0f1da48d067a87d1"


# Debug Config
Debug : True