# Bot Config
Bot :
  # HTTP通信
  http :
    coolq_http_api_ip : "127.0.0.1"
    coolq_http_api_port : "5700"

  # Mysql连接信息
  mysql :
    db_host : "127.0.0.1"
    db_port : 3306
    db_user : "bot_admin"
    db_passwd : "Huawei12#$"
    db_database : "mybot"
    db_charset : "utf8mb4"

  # 管理员信息配置
  admin :
    uid : 3012797743


# 用户管控 不建议改动
Level :
  # 用户权限
  user :
    general : 10
    vip : 50
    admin : 999
  # 群组权限
  group :
    general : 10
    vip : 50
  # 普通用户调用频率限制
  user_limit: 
    enable: True  # or False
    seconds: 10   # user_limit_cycle

# 默认定时任务
Task :
  # 默认监测任务线程
  CYCLE_TASK_DETECT: 
    enable: False
  # 随机发言插件 - 实验性
  BOT_RANDOM_SPEECH:
    enable: False
  # 定时图片发送 - 实验性
  CYCLE_IMAGE_SENDER:
    enable: False


# Plugin Config
Plugin :
  saucenao :
    api_key : ""
    # saucenao触发ascii2d二次搜索的最低相似度
    limit_similarity : 60.0
    # saucenao返回同人本时是否获取同人本信息
    add_doujin_info: True

  bot_img_search :
    # 搜图插件 - 最大消息等待时间,秒
    timeout : 60


# Debug Config
Debug : True