# Bot Config
Bot :
  coolq_http_api_ip : "127.0.0.1"
  coolq_http_api_port : "5700"
  mysql :
    db_host : "127.0.0.1"
    db_port : 3306
    db_user : "bot_admin"
    db_passwd : "Huawei12#$"
    db_database : "mybot"
    db_charset : "utf8mb4"


# Plugin Config
Plugin :
  saucenao :
    api_key : "f8c6827c4a9e6eef82267d5a0f1da48d067a87d1"


# Debug Config
Debug : True
